language: generic
sudo: required
services:
  - docker

before_install:
  - cd complex
  - docker build -t vazarely/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vazarely/multi-client-test npm test

after_success:
  - docker build -t vazarely/multi-client ./client
  - docker build -t vazarely/multi-nginx ./nginx
  - docker build -t vazarely/multi-server ./server
  - docker build -t vazarely/multi-worker ./worker

  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push vazarely/multi-client
  - docker push vazarely/multi-nginx
  - docker push vazarely/multi-server
  - docker push vazarely/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: udemy-multi-docker
  env: UdemyMultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-011946392048
  bucket_path: udemy-multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
