language: generic
sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t vazarely/udemy-docker-and-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true vazarely/udemy-docker-and-kubernetes npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'udemy-docker-and-kubernetes'
  env: 'UdemyDockerAndKubernetes-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-011946392048'
  bucket_path: 'udemy-docker-and-kubernetes'
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
